### ISSUE TITLE
Update help text to reflect more the output files than internals of the GATK pipeline when explaining options.

### ISSUE THREAD

**Issue by oskarvid** [elixir-no-nels/rbFlow-Germline#10]
Instructions unclear, what does "reflect more the output files than internals of the GATK pipeline" mean?

**Comment by kjellp** [comment]
The end user will not have detailed knowledge about the GATK pipelines names of tools for each step, but they do know what the input fastq, final preprocessed bam and final processed vcf files are. The help text should this not refer to HaploTypeCaller, BaseRecalibration etc, but the resulting output files wherever applicable. (Maybe only relevant for -v and -p options?)

**Comment by oskarvid** [comment]
If I remember correctly this option was to save storage space when the pipeline was finished. Instead of saving files that would never be used the function would delete the intermediary bam and vcf files. Obviously the final output files would be saved, but also the BaseRecalibrator output in case the user for instance wanted to rerun the germline part of the pipeline.
So this option could be used for this milestone too. I don't think it makes much sense to base the help text on the fastq file names because the input files could be placed anywhere, or not be in place if it we hardcode where the input files should be, so it should have a static name in my opinion. 

The help text currently says "-k: "Keep all intermediary output files after execution."
The message you're thinking of is in the "slurm-jobnumber.out" file and currently says "Only copying output files from ApplyBQSR and ApplyVQSR back to $OUTPUTDIRECTORY" Where $OUTPUTDIRECTORY is a variable that displays the output directory that the user specified when the pipeline was started.
How about we make the "slurm-jobnumber.out" message say "Only copying final preprocessed bam file and final vcf files."?

Please let me know if you have anything specific in mind.

**Comment by oskarvid** [comment]
After Kjell and I had a meeting on the 31/8 we looked at the updates I have made to the code and concluded that the changes I have made have solved this issue. The code will get put in the repository once we are ready to call this milestone finished.
