### ISSUE TITLE
Clearify if current Singularity version on Colossus is a showstopper for us 

### ISSUE THREAD

**Issue by kjellp** [elixir-no-nels/rbFlow-Germline#15]
We have experienced earlier a problem with the current version of singularity on Colossus being a bit outdated (possibly related to rootsquash behaviour, making access to different NFS mounted HNAS filesystems difficult).  

Is our current implementation (with the last documented switches/flags needed to be used in the singularity command for Colossus executions) "happy enough" for this first production release?

**Comment by oskarvid** [comment]
I have had no complaints and see no reason to upgrade for this milestone. We can definitely consider it for the next milestone.

**Comment by oskarvid** [comment]
I will close this issue since there are no problems at the moment.
