### ISSUE TITLE
Workaround i/o from/to shared filesystem

### ISSUE THREAD

**Issue by kjellp** [elixir-no-nels/rbFlow-Germline#21]
Instead of waiting for the functionality in Colossus to mount /tsd/p172sharedpXX directly to a compute node(update: will not happen this time around), a we should look at this workaround:
1) ./configure (run script) stages the input folder given in -i to the /cluster/projects/p172 area
2) the input data is pulled by the runOnNode sbatch script from /cluster/projects/p172 to the local scratch disk
3) Singularity is started such that the local scratch copy of the input files are being used
4) Output files should be generated on local scratch first 
5) sbatch script must delete the /cluster/projects/p172 copy of the input data before terminating
6) Output files should ideally be copied to the destination specified by -o, but we don't have access to /tsd/p172ncspm (assumed, to be tested). Could the checkFile mechanism be used to get the files back to the submit directory instead? (Ghislain thinks not, to be tested). If not checkFile works: write output temporarily to /cluster/projects/p172 area
7) Copy the output files from /cluster/projects/p172 area to the submit dir inside /tsd/p172ncspm/where/job/was/started (really the -o option) on HNAS
8) Delete the copy of output file from /cluster/project/p172 area

**Comment by oskarvid** [comment]
It works now, it may need polishing for usability purposes, but the files are moved as specified.
