### ISSUE TITLE
Location of rubyFlowLite flag (-b) should be a configuration/installation item, not user exposed choice

### ISSUE THREAD

**Issue by oskarvid** [elixir-no-nels/rbFlow-Germline#8]
The reason for this is because an end user should not be concerned with the rbFlowLite code location, hence this should be hard coded. The current setup needs this to simplify development.

**Comment by oskarvid** [comment]
rbFlowLite has not been installed to a dedicated default location yet, a solution will be put in place in time, but verification of expected proper behavior will wait until rbFlowLite has been installed to this dedicated default location. 

Alternative 1: "Install" rbFlowLite in a custom location to avoid the need to ask TSD staff to install it.
Alternative 2: Install rbFlowLite inside the Singularity image to avoid any risk of install paths failing. The image will need ruby installed in it which will increase the image size (insignificantly?). 
Alternative 3: Ask TSD staff to install rbFlowLite in a standard location, this should be a stable and robust option but also means surrender of direct control of the code.

**Comment by kjellp** [comment]
Is Alt 2 viable? Wouldn't it mean nesting of singularity containers? rubyFlowLite container running a pipeline loading tool container(s)?
I'd vote for Alt 1 over Alt 3.

**Comment by oskarvid** [comment]
Alternative 2 is viable, you don't need to run the tools in singularity if you are in the container already.

I'm fine with alternative 1.
How about placing it in /cluster/projects/p172/rbFlowLite?

**Comment by kjellp** [comment]
Sounds good.


Den fre. 24. aug. 2018, 14:01 skrev Oskar Vidarsson <
notifications@github.com>:

**Comment by oskarvid** [comment]
I've moved rbFlowLite to the /cluster/projects/p172/ directory, I will close this issue once I've verified that it works as expected. This will wait until testing on UH-Sky has finished.

**Comment by oskarvid** [comment]
It worked fine in the latest full NA12878 test, issue closed.
